services:
  postgres:
    image: postgres
    volumes:
      - ./init.sql:/init.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "test"
    ports:
      - "5434:5432"